name: ERT-package-el

on:
  push:
  pull_request:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 28.2
          - release-snapshot
          - snapshot
    steps:
      - name: Set up Emacs
        uses: purcell/setup-emacs@v3.0
        with:
          version: ${{ matrix.emacs_version }}

      # Checks-out repository under $GITHUB_WORKSPACE
      - name: Clone vhdl-ext
        uses: actions/checkout@v2

      - name: Install binaries
        run: |
          cd $GITHUB_WORKSPACE
          test/scripts/setup-env.sh
          test/scripts/install-ts-grammar.sh

      - name: Run ERT tests
        run: |
          cd $GITHUB_WORKSPACE
          make test_package_el

