name: ERT-package-el

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  schedule:
    - cron: '0 0 * * *' # daily

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 29.1
    steps:
      - name: Set up Emacs
        # uses: purcell/setup-emacs@master
        uses: purcell/setup-emacs@v5.0
        with:
          version: ${{ matrix.emacs_version }}

      # Checks-out repository under $GITHUB_WORKSPACE
      - name: Clone vhdl-ext
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install binaries
        run: |
          test-hdl/vhdl/scripts/setup-env.sh
          test-hdl/vhdl/scripts/install-ts-grammar.sh

      - name: Run ERT tests
        run: |
          make pkg_el
